### ISSUE TITLE
LaraFlash Package 

### ISSUE THREAD

**Issue by locemarn** [DevMarketer/LaraFlash#9]
Hey bro, how are you??
In the first, congratulations for your awesome job!!
The LadaFlash work in the test on HomeController, but doesn't work in the manage.posts.create.

Is it necessary put DevMarketer\LaraFlash\LaraFlashServiceProvider::class, in 'provider' and 
the other in 'aliases'??

but does not work here. Can you help me??

sorry for my english!!

**Comment by axieum** [comment]
Are you flashing the message before returning a redirect? If so, you can try `LaraFlash::keep()` though I had no luck with this; am eagerly waiting for a fix.

This is because a redirect counts as 2 requests and thus is only passed to the first request. The keep method aims to persist it across 2 requests.

Remember, you'll need to import the LaraFlash class: `use LaraFlash;`.
